export type Candidate = {
  firstname: string,
  lastname: string,
  dob: string,
  roleid: string,
  email: string,
  password?: string,
  appldate?: string,
  cv?: any,
  phone: string,
  stage?: string,
  status?: string,
  id?: string,
  gender?: "Male" | "Female",
  education?: string,
  experience?: string,
  flag?: string,
  othername?: string,
  jobname?: string,
  tempid?: string,
  coverletter?: string,
  address?: string,
  maritalstatus?: string,
  state?: string,
  lga?: string,
  religion?: string,
  staffid?: string,
  hiredate?: string,
  jobtype?: string,
}

export type Comment = {
  id?: string,
  firstName: string,
  lastName: string,
  comment: string,
  date?: string
}